G12-Wanderwave/Wanderwave

.github/workflows/CI.yaml, .gitignore, app/build.gradle.kts
Closes #52 
Update the CI and gitignore to use the correct signing keys for use in Firebase and Spotify
=> Create signing config

app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/TrackListScreenTest.kt
The issue with the test that sometimes was passing, sometimes wasn't, was because of the flow. This PR aims to resolve this problem (also, pls I would need advice, because I don't know if I should create a new branch and open a pull request even for a small change like that)
=> Solving the test issue

.github/workflows/BuildAPK.yaml
Hopefully this one actually works-
=> Use different GH Action for publishing release

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/SpotifyControllerTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModelTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/spotify/SpotifyController.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/ProfileScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModel.kt
This pull request is only for the user to retrieve his most recently track/album
=> a user can retrieve the most recently listened title

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/SpotifyControllerTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModelTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/spotify/SpotifyController.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/profile/TrackActions.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/tracklist/TrackListItem.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/ProfileScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModel.kt
So this retrieve all the playable items from the spotify main screen, and display them as a scrollable list on the profile screen . I think a new issue to improve this could be to use spotify web API to retrieve the songs from the playlist, but for this, I think it's best to do for the next sprint.
=> Retrieve songs from playlist

dev/README.md, dev/example.gitcommit
Just very simple aliases that I created a while ago and that I thought I would share
They are all very usefull, especially the two new additions today
git cff : automatic commit named ktfmt :)
git rb <branch name> : rebase a branch automatically if possible, else merge it 
How to install is written in the read me
Here is a list of the commands : 
git i : nicer git log
git s : shorter and more efficient git status 
git c : git commit -am 
git undo : reset the last commit
=> aliases example for enhanced productivity

app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/BeaconScreenTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/LoadingScreenTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/SpotifyConnectScreenTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/screens/BeaconScreen.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/screens/LoadingScreen.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/screens/SpotifyConnectScreen.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/screens/components/LoadingScreenTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/data/Track.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/BeaconConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/FirebaseConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/App.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/map/WanderwaveGoogleMap.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/map/WanderwaveMapMarker.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/utils/LoadingScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/BeaconScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/LoginScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/MapScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/SpotifyConnectScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/BeaconViewModel.kt, app/src/main/res/values/strings.xml
I added a beacon screen about how I envision it. 
Since there is no proper navigation yet (Issue #133), the way to test is via the preview or by faking the navigation.
I think it looks quite nice, let me know what you think :)
The idea behind the google map is to show on a map where the beacon is (WIP). Maybe in the future, this can be replaced by information about the beacon's creator or something.
=> Beacon screen UI

app/build.gradle.kts, app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/AuthenticationControllerTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/LoginScreenViewModelTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/SpotifyConnectScreenViewModelTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/di/AuthenticationModule.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/auth/AuthenticationController.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/auth/AuthenticationUserData.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/LoginScreenViewModel.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/SpotifyConnectScreenViewModel.kt, gradle/libs.versions.toml
This is basically the same as #111 but into a up to date feature branch
=> [Feature][spotify auth] add authentication controller

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/SpotifyControllerTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/TrackListScreenTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/TrackListViewModelTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/spotify/SpotifyController.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/App.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/player/MiniPlayer.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/player/SurroundWithMiniPlayer.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/TrackListScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/TrackListViewModel.kt
Almost ready to merge, I just need to write some tests for it. Otherwise it is fully functional.
=> 116 add the play functionality to the spotify controller

app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/EditProfileTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/ProfileTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModelTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/navigation/NavigationActions.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/App.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/profile/TrackActions.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/EditProfileScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/ProfileScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/SelectSongScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModel.kt
This finishes the issue #129 and #131. So basically, now from the profile screen, the user can click on the button "Add track to top songs list", and he can add a playlist to the songlist. We still have to implement the web aPI in order to recover the songs from the playlist.
=> Song select screen

app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/PlayerScreenTest.kt
Fix the bug that could get to the main someway
=> [BUGFIX] Fixing the main bug with player screen test

app/build.gradle.kts, app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/AuthenticationControllerTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/LoginScreenViewModelTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/di/AuthenticationModule.kt, app/src/main/java/ch/epfl/cs311/wanderwave/di/OkHttpModule.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/auth/AuthenticationController.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/spotify/SpotifyController.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/LoginScreenViewModel.kt, gradle/libs.versions.toml
This PR changes the Firebase authentication from anonymous to using Spotify via the Firebase Functions.
=> [Spotify auth] Get token from Firebase Functions

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/DataClassesTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/data/ProfileTrackAssociation.kt
This is a very small PR to just create the data class that associate a user with a track
=> Create the data class ProfileTrackAssociation

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/BeaconConnectionTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/DataClassesTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/TrackListScreenTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/di/ConnectionModule.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/BeaconConnection.kt
Test Beacon screen to pass the coverage of the branch
=> Feature/beacon screen/testing

app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/BeaconConnection.kt
=> Feature/beacon screen/cleanup

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/BeaconConnectionTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/DataClassesTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/BeaconConnection.kt
=> Testing (more of course)

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/BeaconConnectionTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/DataClassesTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/ProfileConnectionTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/di/ConnectionModule.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/data/Beacon.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/data/Profile.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/data/ProfileTrackAssociation.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/BeaconConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/ProfileConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/LoginScreen.kt
Implement the new firebase beacon structure
=> Feature/profile integration/firebase fix

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/BeaconConnectionTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/di/RepositoryModule.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/BeaconConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/FirebaseConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/ProfileConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/TrackConnection.kt
The goal of this PR is to inject Firebase instead of instantiating it every time like we were doing.
This mainly concerns testing and the different connection files
=> Use dependency injection for the firebase database

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/BeaconConnectionTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/utils/BeaconPlacerTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/BeaconConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/FirebaseConnection.kt
@mbouaissi 
This PR add the fact that when retrieving the ID, the tracks that are in the beacon are also added to firebase.
=> add item and get id now add the tracks in beacon connection

app/build.gradle.kts, app/src/main/java/ch/epfl/cs311/wanderwave/model/data/Beacon.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/data/Profile.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/BeaconConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/FirebaseConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/ProfileConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/TrackConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/spotify/SpotifyController.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/utils/BeaconGenerator.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/utils/BeaconPlacer.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/App.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/ProfileScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/ProfileViewOnlyScreen.kt, gradle/libs.versions.toml
The PR aims at fixing the sonar cloud issues, it fixes all high importances issues, and 80% of all the mid importance
=> Fix sonarcloud issues

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/ProfileConnectionTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/EditProfileTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/ProfileTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModelTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/ProfileConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/EditProfileScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/ProfileScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/ProfileViewOnlyScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModel.kt
Creates the user profile on Firestore if it doesn't exist yet, and loads it otherwise
=> Feature/link profile to auth/persist profile

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/SpotifyControllerTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/TrackListScreenTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModelTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/SpotifySongsActionsTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/TrackListViewModelTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/data/ListType.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/data/viewModelType.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/spotify/SpotifyController.kt, app/src/main/java/ch/epfl/cs311/wanderwave/navigation/NavigationActions.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/App.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/profile/TrackActions.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/tracklist/TrackList.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/ProfileScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/ProfileViewOnlyScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/SelectSongScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/TrackListScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModel.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/TrackListViewModel.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/interfaces/SpotifySongsActions.kt
Now, the user is able to go to his profile, select if he wants to see his top songs or liked songs, and add them to the playlist. This PR also refactor a little bit the code
Closes #267
=> Feature/web api/recover liked songs function

app/src/androidTest/java/ch/epfl/cs311/wanderwave/endToEnd/LoginAndUseMediaControllerEndToEndTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/AppBottomBarTest.kt
I've adapted the test to the new flow and fixed some minor issues
=> Updated the test

app/src/main/java/ch/epfl/cs311/wanderwave/model/spotify/SpotifyController.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/player/ExclusivePlayer.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/player/MiniPlayer.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/TrackListViewModel.kt
The progress bars in both media players are now in sync with the actual song
=> Fix the progress bar UI

app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/BeaconScreenTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/BeaconScreenViewModelTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/BeaconScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/BeaconViewModel.kt, app/src/main/res/values/strings.xml
This allows users to manually add a track to a beacon.
Will be fully functional once #318 is merged
=> Adapt the add track button in the beaconscreen

app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/BeaconScreenTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/BeaconScreenViewModelTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/BeaconScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/BeaconViewModel.kt, app/src/main/res/values/strings.xml
Reverts G12-Wanderwave/Wanderwave#334
=> Revert "Adapt the add track button in the beaconscreen"

app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/map/BeaconMapMarker.kt
This PR just comment the part where we set up the logo of the beacons, so that the application is more fluid
=> Comment the beacon logo

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/TrackConnectionTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/BeaconScreenTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/BeaconScreenViewModelTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/data/viewModelType.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/BeaconConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/TrackConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/App.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/tracklist/TrackList.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/BeaconScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/BeaconViewModel.kt
This allows users to add songs to a beacon from the BeaconScreen
=> Fixed the issue in BeaconScreen

app/src/main/java/ch/epfl/cs311/wanderwave/model/spotify/SpotifyController.kt
Something got lost when merging
=> fix bug that would not add songs to recent list

app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/BeaconScreen.kt
Reorganized the buttons and made the UI adapt to the viewmodel state
=> Modified the add track to beacon UI

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/BeaconConnectionTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/ProfileConnectionTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/BeaconScreenTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/ProfileTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/BeaconScreenViewModelTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/BeaconConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/ProfileConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/repository/BeaconRepository.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/repository/ProfileRepository.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/BeaconViewModel.kt
Some cleaning up with the new Firebase functionality, as well as correctly setting the users profile when adding a track to a beacon
=> Feature/link profile to auth/set user profile in track association

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/DataClassesTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/ui/BeaconScreenTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModelTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/data/ProfileTrackAssociation.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/BeaconConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/TrackConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/App.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/tracklist/TrackList.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/tracklist/TrackListItem.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/BeaconScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModel.kt
This allows users to like (and unlike) songs in beacons, which adds them to a dedicated list and increases the song's OP's like counter.
Closes #309
=> Feature/like songs/like locally

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/BeaconConnectionTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/DataClassesTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/data/Profile.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/data/ProfileTrackAssociation.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/BeaconConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/FirebaseConnection.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/TrackConnection.kt
This PR requested by imade, implements the back end for the new track profile assotiation including ; 
- Bit of refactoring for the track profile assotiation (add the toMap and from functions)
- Bit of refactoring in the beaconConnection (use the to map 2 times and the from function)
- Implementation of the actual code in the trackConnection and BeaconConnection
=> Feature/like songs/firebase profile track assotiation

app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/DataClassesTest.kt, app/src/androidTest/java/ch/epfl/cs311/wanderwave/model/ProfileConnectionTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/data/Profile.kt, app/src/main/java/ch/epfl/cs311/wanderwave/model/remote/ProfileConnection.kt
In this PR, I store the liked songs on the profile in firebase
#close #308
=>  store the liked songs on the profile

app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/TrackListScreen.kt
This allows users to see the songs they liked in the TrackListScreen
Closes #371
=> Added the proper liked songs list to the TrackListScreen

app/src/androidTest/java/ch/epfl/cs311/wanderwave/viewmodel/TrackListViewModelTest.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/components/tracklist/TrackListItem.kt, app/src/main/java/ch/epfl/cs311/wanderwave/ui/screens/TrackListScreen.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/ProfileViewModel.kt, app/src/main/java/ch/epfl/cs311/wanderwave/viewmodel/TrackListViewModel.kt, app/src/main/res/values/strings.xml
This PR add the profile of the album + change the ui of the track list 
Closes #413 
Closes #365
=> Improve track list screen
